- name: Install Docker
  package:
    name: docker-ce
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes  