#SPDX-License-Identifier: MIT-0
---
# vars file for install_docker
# docker_repo: "https://download.docker.com/linux/centos/docker-ce.repo"
docker_repo: "https://download.docker.com/linux/fedora/docker-ce.repo"
