services:
  db:
    image: mysql
    restart: always
    env_file: ../.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ../game/serpent-surge-main/db/init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - private
    ports:
      - 3306:3306
  backend:
    build:
      dockerfile: ./docker/backend.Dockerfile
      context: ../
      args:
      - NODE_ENV=production
    command: npm start
    env_file: ../.env
    environment:
      - NODE_ENV=production
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - 3000:3000
    networks:
      - private
    depends_on:
      - db
    restart: on-failure
  frontend:
    build:
      dockerfile: ./docker/frontend.Dockerfile
      context: ../
    ports:
      - 80:80
    networks:
      - public
      - private
    depends_on:
      - backend
networks:
  public:
  private:
