- name: Docker compose up
  hosts: all
  become: true
  tasks:
  - name: Run docker compose with env var
    community.docker.docker_compose_v2:
      project_src: serpent-surge
      build: always
      files: docker/compose.yaml
      state: present
      # restarted: true
      # environment:
      #   DB_HOST: "$RDP_ENDPOINT"       
      #   DB_PASSWORD: "${{ DB_PASSWORD }} \"
      #   DB_USER: "node_user"
      #   DB_NAME: "serpent_surge_db"
      #   PUBLIC_DNS_NAME: "kopakoserpent.ddns.net"
      #   CERTBOT_EMAIL: "kopandima@gmail.com"