- name: Docker compose up
  hosts: all
  become: true
  tasks:
  - name: Run docker compose with env var
    community.docker.docker_compose_v2:
      project_src: serpent-surge/docker
      build: always
      services:
        - frontend
        - backend
      state: present
      env_files:
        - .env
