name: Ansible

on:
  workflow_run:
    workflows: ["Terraform"]
    types: [completed]

jobs:
  prepare_ansible:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1

    steps:
    - name: Checkout repo to github runer 
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download terraform state file
      run: aws s3 cp s3://serpent-surge-s3/network/terraform.tfstate ./
    
    - name: Extract ec2_endpoint value
      run: echo "EC2_ENDPOINT=$(jq -e ".outputs.ec2_endpoint.value" terraform.tfstate)" >> $GITHUB_ENV
    
    - name: Extract rdp_endpoint value
      run: echo "RDP_ENDPOINT=$(jq -e ".outputs.rdp_endpoint.value" terraform.tfstate)" >> $GITHUB_ENV

    - name: Check home
      run: echo $HOME

    - name: Check current dir
      run: echo $PWD

    - name: Check dir
      run: tree

    - name: Configure Ansible
      run: |
        sudo apt update
        sudo pipx inject ansible-core jmespath
        ansible-playbook --version
        echo "[awshosts]" >> ansible_hosts
        echo $EC2_ENDPOINT >> ansible_hosts
        mv ansible_hosts $HOME/work/serpent-surge/serpent-surge/ansible/ansible_hosts
        cat $HOME/work/serpent-surge/serpent-surge/ansible/ansible_hosts
    - name: Ansible install docker
      uses: dawidd6/action-ansible-playbook@v4
      with:
        playbook: docker-install.yml
        directory: ansible/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [awshosts]
          $EC2_ENDPOINT
        options: |
          --verbose
    - name: Ansible Docker compose up
      uses: dawidd6/action-ansible-playbook@v4
      with:
        playbook: docker_compose_up.yaml
        directory: ansible/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [awshosts]
          $EC2_ENDPOINT
        options: |
          --verbose
        env:
          DB_HOST=$RDP_ENDPOINT \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_USER=node_user \
          DB_NAME=serpent_surge_db \
          PUBLIC_DNS_NAME=kopakoserpent.ddns.net \
          CERTBOT_EMAIL=kopandima@gmail.com \
          docker compose up --detach frontend backend

