name: Ansible

on:
  workflow_run:
    workflows: ["Terraform"]
    types: [completed]

jobs:
  prepare_ansible:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1

    steps:
    - name: Checkout repo to github runer 
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download terraform state file
      run: aws s3 cp s3://serpent-surge-s3/network/terraform.tfstate ./
    
    - name: Extract ec2_endpoint value
      run: echo "EC2_ENDPOINT=$(jq -e ".outputs.ec2_endpoint.value" terraform.json)" >> $GITHUB_ENV
    
    - name: Extract rdp_endpoint value
      run: echo "RDP_ENDPOINT=$(jq -e ".outputs.rdp_endpoint.value" terraform.json)" >> $GITHUB_ENV

    - name: Configure Ansible
      run: |
        sudo apt update
        sudo pipx inject ansible-core jmespath
        ansible-playbook --version
        echo "[web]" >> ansible_hosts
        echo $EC2_ENDPOINT >> ansible_hosts
        mv ansible_hosts $HOME/serpent-surge/ansible/
        cat $HOME/serpent-surge/ansible/ansible_hosts
  ansible:
    runs-on: ubuntu-latest
    needs: prepare_ansible
    steps:
    - name: Ansible install docker
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: docker-install.yml
        directory: $HOME/serpent-surge/ansible/
        key: ${{secrets.SSH_PRIVATE_KEY}}
        options: |
          --inventory ansible_hosts
          --verbose
    - name: Ansible Docker compose up
      run: |
        DB_HOST=$RDP_ENDPOINT \
        DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
        DB_USER=node_user \
        DB_NAME=serpent_surge_db \
        PUBLIC_DNS_NAME=kopakoserpent.ddns.net \
        CERTBOT_EMAIL=kopandima@gmail.com \
        docker compose up --detach frontend backend
      working-directory: $HOME/serpent-surge/docker

